spring:
  profiles:
    active: test
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}

  mvc:
    dispatch-options-request: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_TEST_URL}/${DB_TEST_DATABASE}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: ${SMTP_HOST}
    port: 465
    username: ${SMTP_ID}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: ${SMTP_HOST}
  cache:
    type: redis

server:
  shutdown: graceful

logging:
  level:
    root: info

timezone: ${TIMEZONE}
smtp-id: ${SMTP_ID}

kakao-cid: TC0ONETIME
kakao-host: https://kapi.kakao.com/v1/payment
kakao-adminkey: ${KAKAO_ADMIN_KEY}

toss-host: https://api.tosspayments.com/v1/payments
toss-client-key: ${TOSS_CLIENT_KEY}
toss-secret-key: ${TOSS_SECRET_KEY}
test-url : ${TEST_URL}


